
import { Comic } from './types';

export const INITIAL_COMICS: Comic[] = [
  {
    id: '1',
    title: 'Absolute Batman #15',
    writer: 'Scott Snyder',
    artist: 'Nick Dragotta',
    publisher: 'DC Comics',
    year: 2025,
    description: 'The groundbreaking new vision of the Dark Knight continues in this bold reimagining of Batman for a new era.',
    coverUrl: 'https://static.dc.com/2025-12/T2349200155001_000_HD_HD.jpg?w=640',
  },
  {
    id: '2',
    title: 'Ultimate Spider-Man #23',
    writer: 'Jonathan Hickman',
    artist: 'Marco Checchetto',
    publisher: 'Marvel Comics',
    year: 2025,
    description: 'Peter Parker juggles family life and spider-heroics in this fresh take on the ultimate web-slinger.',
    coverUrl: 'https://cdn.marvel.com/u/prod/marvel/i/mg/c/c0/6925e5ddac7a7/clean.jpg',
  },
  {
    id: '3',
    title: 'The Will of Doom #1',
    writer: 'Al Ewing',
    artist: 'Cafu',
    publisher: 'Marvel Comics',
    year: 2025,
    description: 'Doctor Doom takes center stage in this epic new series exploring the will and ambition of Marvel\'s greatest villain.',
    coverUrl: 'https://cdn.marvel.com/u/prod/marvel/i/mg/d/60/693323d118283/clean.jpg',
  },
  {
    id: '4',
    title: 'The Woods Vol. 1',
    writer: 'James Tynion IV',
    artist: 'Michael Dialynas',
    publisher: 'Boom! Studios',
    year: 2014,
    description: 'When a high school is suddenly transported into an alien wilderness, students must survive in this mysterious and dangerous new world.',
    coverUrl: 'https://s3.amazonaws.com/comicgeeks/comics/covers/large-4957493.jpg?1732753481',
  },
  {
    id: '5',
    title: 'Something is Killing the Children #45',
    writer: 'James Tynion IV',
    artist: 'Werther Dell\'Edera',
    publisher: 'Boom! Studios',
    year: 2025,
    description: 'Erica Slaughter continues her hunt for monsters that prey on children in this chilling horror series.',
    coverUrl: 'https://s3.amazonaws.com/comicgeeks/comics/covers/large-7408531.jpg?1764859140',
  },
  {
    id: '6',
    title: 'Void Rivals #25',
    writer: 'Robert Kirkman',
    artist: 'Lorenzo De Felici',
    publisher: 'Image Comics',
    year: 2025,
    description: 'Two soldiers from warring species must work together to survive in this sci-fi epic from the Energon Universe.',
    coverUrl: 'https://imagecomics.com/files/releases/void-rivals-25-CVRA.jpg',
  }
];

// Starter picks for first-time users (Continuity = 0)
// Order reflects onboarding flow, not quality
export const STARTER_PICKS: Comic[] = [
  {
    id: 'starter-1',
    title: 'Fables, Vol. 1: Legends in Exile',
    writer: 'Bill Willingham',
    artist: 'Lan Medina',
    publisher: 'DC Vertigo',
    year: 2002,
    description: 'A mature reimagining of fairy tales through the lens of modern society.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1563899426-L.jpg',
  },
  {
    id: 'starter-2',
    title: 'Hawkeye Vol. 1: My Life as a Weapon',
    writer: 'Matt Fraction',
    artist: 'David Aja',
    publisher: 'Marvel Comics',
    year: 2013,
    description: 'A fun, character-driven superhero story.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/0785165622-L.jpg',
  },
  {
    id: 'starter-3',
    title: 'The Jetsons',
    writer: 'Jimmy Palmiotti',
    artist: 'Pier Brito',
    publisher: 'DC Comics',
    year: 2017,
    description: 'A thoughtful sci-fi story using characters we grew up with.',
    coverUrl: 'https://static.dc.com/dc/files/default_images/JETSONS_170-001_HD_5b8488b66da828.82577836.jpg?w=640',
  },
  {
    id: 'starter-4',
    title: 'Wytches',
    writer: 'Scott Snyder',
    artist: 'Jock',
    publisher: 'Image Comics',
    year: 2014,
    description: 'A dark, unsettling horror story that lingers.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1632153807-L.jpg',
  },
];
