
import { Comic } from './types';

export const INITIAL_COMICS: Comic[] = [
  {
    id: '1',
    title: 'Watchmen',
    writer: 'Alan Moore',
    artist: 'Dave Gibbons',
    publisher: 'DC Comics',
    year: 1986,
    description: 'In a world where the mere presence of American superheroes changed history, the US won the Vietnam War, Nixon is still president, and the Cold War is in full effect.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/0930289234-L.jpg',
  },
  {
    id: '2',
    title: 'Saga',
    writer: 'Brian K. Vaughan',
    artist: 'Fiona Staples',
    publisher: 'Image Comics',
    year: 2012,
    description: 'The story of Alana and Marko, two soldiers from opposite sides of a never-ending galactic war, who fall in love and risk everything to bring a new life into a dangerous old universe.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1607066017-L.jpg',
  },
  {
    id: '3',
    title: 'The Sandman',
    writer: 'Neil Gaiman',
    artist: 'Sam Kieth',
    publisher: 'DC Vertigo',
    year: 1989,
    description: 'The story of Morpheus, the King of Dreams, and his attempts to rebuild his kingdom after being held prisoner for 70 years.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1401225756-L.jpg',
  },
  {
    id: '4',
    title: 'Maus',
    writer: 'Art Spiegelman',
    artist: 'Art Spiegelman',
    publisher: 'Pantheon Books',
    year: 1980,
    description: 'A haunting and innovative graphic novel that uses animals to tell the story of the author\'s father\'s experiences during the Holocaust.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/0394747232-L.jpg',
  },
  {
    id: '5',
    title: 'Batman: The Dark Knight Returns',
    writer: 'Frank Miller',
    artist: 'Frank Miller',
    publisher: 'DC Comics',
    year: 1986,
    description: 'An aged Bruce Wayne comes out of retirement to clean up the streets of Gotham in a gritty, dystopian future.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1563893428-L.jpg',
  },
  {
    id: '6',
    title: 'Monstress',
    writer: 'Marjorie Liu',
    artist: 'Sana Takeda',
    publisher: 'Image Comics',
    year: 2015,
    description: 'Set in an alternate matriarchal Asia, Monstress tells the story of a teenage girl who is struggling to survive the trauma of war.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1632157098-L.jpg',
  }
];

// Starter picks for first-time users (Continuity = 0)
// Order reflects onboarding flow, not quality
export const STARTER_PICKS: Comic[] = [
  {
    id: 'starter-1',
    title: 'Fables, Vol. 1: Legends in Exile',
    writer: 'Bill Willingham',
    artist: 'Lan Medina',
    publisher: 'DC Vertigo',
    year: 2002,
    description: 'A mature reimagining of fairy tales through the lens of modern society.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1563899426-L.jpg',
  },
  {
    id: 'starter-2',
    title: 'Hawkeye Vol. 1: My Life as a Weapon',
    writer: 'Matt Fraction',
    artist: 'David Aja',
    publisher: 'Marvel Comics',
    year: 2013,
    description: 'A fun, character-driven superhero story.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/0785165622-L.jpg',
  },
  {
    id: 'starter-3',
    title: 'The Jetsons',
    writer: 'Jimmy Palmiotti',
    artist: 'Pier Brito',
    publisher: 'DC Comics',
    year: 2017,
    description: 'A thoughtful sci-fi story using characters we grew up with.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1401277489-L.jpg',
  },
  {
    id: 'starter-4',
    title: 'Wytches',
    writer: 'Scott Snyder',
    artist: 'Jock',
    publisher: 'Image Comics',
    year: 2014,
    description: 'A dark, unsettling horror story that lingers.',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/1632153807-L.jpg',
  },
];
